### ISSUE TITLE
Git history

### ISSUE THREAD

**Issue by Skallwar** [repnop/sbi#1]
Hi,

Thanks for working on this crate!

I noticed that your master branch does not include the commits from @akiekintveld. Maybe you could rebase your branch on top of akiekintveld/sbi/master to keep the history.

Anyway thanks for keeping this crate up to date with the SBI specification, don't hesitate to create issues, I might try to help from time to time

**Comment by repnop** [comment]
The reason that there is no commit history from their repo is because my work isn't based on it, its an independent project that I created for my own RISC-V OS that I've pulled out from the OS repository into its own separate one so I can publish it (hopefully soon! I've been unfortunately quite busy and haven't had the chance to flesh everything out yet, but its close, just documentation and tests left to add). So, for that reason, I don't think it makes much sense to rebase my work on top of theirs since they're not really related.

**Comment by Skallwar** [comment]
My bad then. Keep up the good work

**Comment by repnop** [comment]
@Skallwar I just published the new version of the crate to crates.io FYI! Let me know if you have any questions/comments/suggestions after trying it out :+1:

**Comment by Skallwar** [comment]
Thanks! I will give it a spin. Don't hesitate to create issues (and ping me maybe) for future version of the SBI standard or bug in the crate I will be happy to help
